"""Self-contained HTML report generator for AuditML audits.

Produces a single ``report.html`` file with all charts embedded as inline
SVG (generated by matplotlib).  No internet connection required — the file
opens directly in any modern browser.
"""

from __future__ import annotations

import base64
import io
import textwrap
from datetime import datetime
from pathlib import Path

import numpy as np

# ── Chart helpers (matplotlib → inline SVG) ────────────────────────────────

_PALETTE = ["#6366f1", "#f59e0b", "#22c55e", "#ef4444", "#a78bfa", "#38bdf8"]
_ATTACK_LABELS = {
    "mia_threshold":      "Threshold MIA",
    "mia_shadow":         "Shadow MIA",
    "model_inversion":    "Model Inversion",
    "attribute_inference": "Attribute Inference",
}


def _fig_to_svg(fig) -> str:
    """Convert a matplotlib figure to an inline SVG string."""
    import matplotlib.pyplot as plt
    buf = io.StringIO()
    fig.savefig(buf, format="svg", bbox_inches="tight")
    plt.close(fig)
    svg = buf.getvalue()
    # Strip the XML declaration so it embeds cleanly in HTML
    if svg.startswith("<?xml"):
        svg = svg[svg.index("<svg"):]
    return svg


def _setup_ax(ax):
    """Apply a clean, minimal style to an axes object."""
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_color("#e2e8f0")
    ax.spines["bottom"].set_color("#e2e8f0")
    ax.tick_params(colors="#475569", labelsize=9)
    ax.xaxis.label.set_color("#475569")
    ax.yaxis.label.set_color("#475569")
    ax.title.set_color("#0f172a")
    ax.set_facecolor("#ffffff")
    ax.grid(True, color="#f1f5f9", linewidth=0.8)


def svg_roc_curves(attack_results: dict) -> str:
    """Overlaid ROC curves for all attacks."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from sklearn.metrics import auc, roc_curve

    fig, ax = plt.subplots(figsize=(5.2, 4))
    fig.patch.set_facecolor("#ffffff")
    _setup_ax(ax)

    for i, (name, (_, result)) in enumerate(attack_results.items()):
        try:
            fpr, tpr, _ = roc_curve(result.ground_truth, result.confidence_scores)
            auc_val = auc(fpr, tpr)
            label = _ATTACK_LABELS.get(name, name)
            ax.plot(fpr, tpr, color=_PALETTE[i % len(_PALETTE)],
                    linewidth=2, label=f"{label}  (AUC={auc_val:.3f})")
        except Exception:
            continue

    ax.plot([0, 1], [0, 1], "--", color="#cbd5e1", linewidth=1)
    ax.set_xlabel("False Positive Rate", fontsize=10)
    ax.set_ylabel("True Positive Rate", fontsize=10)
    ax.set_title("ROC Curves", fontsize=12, fontweight="bold", pad=12)
    ax.legend(fontsize=8, framealpha=0.9, edgecolor="#e2e8f0")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1.02)

    return _fig_to_svg(fig)


def svg_score_distribution(name: str, result) -> str:
    """Member vs non-member confidence score histogram for one attack."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    scores = np.array(result.confidence_scores)
    gt = np.array(result.ground_truth)
    member_scores = scores[gt == 1]
    nonmember_scores = scores[gt == 0]

    fig, ax = plt.subplots(figsize=(5.2, 3.5))
    fig.patch.set_facecolor("#ffffff")
    _setup_ax(ax)

    bins = np.linspace(scores.min(), scores.max(), 30)
    ax.hist(member_scores, bins=bins, alpha=0.65, color="#6366f1",
            label="Members", density=True)
    ax.hist(nonmember_scores, bins=bins, alpha=0.65, color="#f59e0b",
            label="Non-members", density=True)

    label = _ATTACK_LABELS.get(name, name)
    ax.set_xlabel("Confidence Score", fontsize=10)
    ax.set_ylabel("Density", fontsize=10)
    ax.set_title(f"Score Distribution — {label}", fontsize=11,
                 fontweight="bold", pad=10)
    ax.legend(fontsize=9, framealpha=0.9, edgecolor="#e2e8f0")

    return _fig_to_svg(fig)


def svg_comparison_bar(attack_metrics: dict[str, dict]) -> str:
    """Horizontal bar chart comparing AUC-ROC across all attacks."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    names = [_ATTACK_LABELS.get(n, n) for n in attack_metrics]
    aucs = [m.get("auc_roc", 0.0) for m in attack_metrics.values()]

    # Sort by AUC descending
    pairs = sorted(zip(names, aucs), key=lambda x: x[1], reverse=True)
    names, aucs = zip(*pairs) if pairs else ([], [])

    def bar_color(v: float) -> str:
        if v >= 0.75:
            return "#ef4444"
        if v >= 0.60:
            return "#f59e0b"
        return "#22c55e"

    colors = [bar_color(v) for v in aucs]

    fig, ax = plt.subplots(figsize=(5.2, max(2.5, len(names) * 0.7 + 0.8)))
    fig.patch.set_facecolor("#ffffff")
    _setup_ax(ax)

    bars = ax.barh(names, aucs, color=colors, height=0.55)
    ax.axvline(0.5, color="#94a3b8", linewidth=1, linestyle="--", alpha=0.7)
    ax.set_xlim(0, 1)
    ax.set_xlabel("AUC-ROC", fontsize=10)
    ax.set_title("Attack Comparison", fontsize=12, fontweight="bold", pad=12)

    for bar, val in zip(bars, aucs):
        ax.text(val + 0.01, bar.get_y() + bar.get_height() / 2,
                f"{val:.3f}", va="center", ha="left", fontsize=9,
                color="#475569", fontweight="600")

    ax.invert_yaxis()

    return _fig_to_svg(fig)


def svg_dp_comparison(
    baseline_metrics: dict[str, dict],
    dp_metrics: dict[str, dict],
) -> str:
    """Grouped bar chart: baseline vs DP model AUC-ROC per attack."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    names = list(baseline_metrics.keys())
    labels = [_ATTACK_LABELS.get(n, n) for n in names]
    base_aucs = [baseline_metrics[n].get("auc_roc", 0.0) for n in names]
    dp_aucs = [dp_metrics.get(n, {}).get("auc_roc", 0.0) for n in names]

    x = np.arange(len(labels))
    width = 0.35

    fig, ax = plt.subplots(figsize=(max(5.2, len(labels) * 1.4), 4))
    fig.patch.set_facecolor("#ffffff")
    _setup_ax(ax)

    ax.bar(x - width / 2, base_aucs, width, label="Baseline", color="#6366f1", alpha=0.85)
    ax.bar(x + width / 2, dp_aucs, width, label="DP Model", color="#22c55e", alpha=0.85)
    ax.axhline(0.5, color="#94a3b8", linewidth=1, linestyle="--", alpha=0.7)

    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=15, ha="right", fontsize=9)
    ax.set_ylabel("AUC-ROC", fontsize=10)
    ax.set_title("Baseline vs DP Model — AUC-ROC", fontsize=12,
                 fontweight="bold", pad=12)
    ax.set_ylim(0, 1)
    ax.legend(fontsize=9, framealpha=0.9, edgecolor="#e2e8f0")

    return _fig_to_svg(fig)


def _recon_to_b64_png(arr: np.ndarray) -> str:
    """Convert a numpy image array (C,H,W) or (H,W) to a base64 PNG string."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    if arr.ndim == 4:
        arr = arr[0]  # (1,C,H,W) → (C,H,W)
    if arr.ndim == 3:
        img = arr.transpose(1, 2, 0)  # C,H,W → H,W,C
        img = (img - img.min()) / (img.max() - img.min() + 1e-8)
        if img.shape[2] == 1:
            img = img[:, :, 0]
    else:
        img = (arr - arr.min()) / (arr.max() - arr.min() + 1e-8)

    fig, ax = plt.subplots(figsize=(1.8, 1.8))
    fig.patch.set_facecolor("#0f172a")
    ax.imshow(img, cmap="gray" if img.ndim == 2 else None)
    ax.axis("off")
    fig.tight_layout(pad=0)

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=80, bbox_inches="tight",
                facecolor="#0f172a")
    plt.close(fig)
    return base64.b64encode(buf.getvalue()).decode()


# ── Risk level helper ───────────────────────────────────────────────────────

def _risk_level(attack_metrics: dict[str, dict]) -> tuple[str, str, str]:
    """Return (label, css_class, description) based on worst AUC."""
    if not attack_metrics:
        return "UNKNOWN", "risk-unknown", "No attacks were run."
    max_auc = max(m.get("auc_roc", 0.0) for m in attack_metrics.values())
    if max_auc >= 0.75:
        return "HIGH RISK", "risk-high", "Significant privacy leakage detected."
    if max_auc >= 0.65:
        return "MODERATE RISK", "risk-moderate", "Noticeable leakage — consider DP training."
    if max_auc >= 0.55:
        return "LOW RISK", "risk-low", "Minor leakage detected. Monitor carefully."
    return "SAFE", "risk-safe", "No significant leakage detected across all attacks."


def _auc_badge(val: float) -> str:
    if val >= 0.75:
        return f'<span class="badge badge-red">{val:.4f}</span>'
    if val >= 0.65:
        return f'<span class="badge badge-orange">{val:.4f}</span>'
    if val >= 0.55:
        return f'<span class="badge badge-yellow">{val:.4f}</span>'
    return f'<span class="badge badge-green">{val:.4f}</span>'


# ── Main HTML builder ───────────────────────────────────────────────────────

def generate_html_report(
    output_dir: Path,
    experiment_name: str,
    attack_results: dict,
    dp_attack_results: dict | None,
    attack_metrics: dict[str, dict],
    dp_attack_metrics: dict[str, dict] | None,
    model_accuracy: dict[str, float] | None,
    epsilon: float | None,
) -> Path:
    """Build a self-contained HTML report and save it to *output_dir/report.html*.

    Parameters
    ----------
    output_dir:
        Directory to write ``report.html`` into.
    experiment_name:
        Name shown in the report header.
    attack_results:
        ``{name: (attack_obj, AttackResult)}`` for the baseline model.
    dp_attack_results:
        Same structure for the DP model, or ``None``.
    attack_metrics:
        Pre-computed metrics dict ``{name: {accuracy, auc_roc, ...}}``.
    dp_attack_metrics:
        Same for the DP model, or ``None``.
    model_accuracy:
        ``{"baseline": float, "dp": float}`` utility scores.
    epsilon:
        DP epsilon, or ``None``.

    Returns
    -------
    Path
        The path to the generated ``report.html``.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    risk_label, risk_cls, risk_desc = _risk_level(attack_metrics)

    # ── Charts ─────────────────────────────────────────────────────────
    roc_svg = svg_roc_curves(attack_results) if attack_results else ""

    dist_svgs: list[tuple[str, str]] = []
    for name, (_, result) in attack_results.items():
        try:
            dist_svgs.append((_ATTACK_LABELS.get(name, name),
                               svg_score_distribution(name, result)))
        except Exception:
            pass

    comp_svg = svg_comparison_bar(attack_metrics) if len(attack_metrics) >= 2 else ""

    dp_comp_svg = ""
    if dp_attack_results and dp_attack_metrics:
        try:
            dp_comp_svg = svg_dp_comparison(attack_metrics, dp_attack_metrics)
        except Exception:
            pass

    # ── Model inversion reconstructions ────────────────────────────────
    recon_html = ""
    for name, (attack, _) in attack_results.items():
        if name == "model_inversion" and hasattr(attack, "reconstructions") and attack.reconstructions:
            cards = ""
            for cls in sorted(attack.reconstructions):
                b64 = _recon_to_b64_png(attack.reconstructions[cls])
                conf = attack.reconstruction_confidences.get(cls, 0.0)
                cards += f"""
                <div class="recon-card">
                  <img src="data:image/png;base64,{b64}" alt="Class {cls}" />
                  <div class="recon-label">Class {cls}</div>
                  <div class="recon-conf">{conf:.3f}</div>
                </div>"""
            recon_html = f"""
            <section>
              <h2>🖼️ Model Inversion Reconstructions</h2>
              <p class="section-sub">
                Gradient-reconstructed images per class. Higher confidence means the
                model more strongly memorised that class's visual pattern.
              </p>
              <div class="recon-grid">{cards}</div>
            </section>"""
            break

    # ── Metrics table rows ──────────────────────────────────────────────
    table_rows = ""
    for name, m in attack_metrics.items():
        label = _ATTACK_LABELS.get(name, name)
        acc = m.get("accuracy", 0.0)
        auc = m.get("auc_roc", 0.0)
        f1 = m.get("f1", 0.0)
        prec = m.get("precision", 0.0)
        rec = m.get("recall", 0.0)
        tpr1 = m.get("tpr_at_1fpr", 0.0)
        table_rows += f"""
        <tr>
          <td class="name-cell">{label}</td>
          <td>{acc:.4f}</td>
          <td>{_auc_badge(auc)}</td>
          <td>{f1:.4f}</td>
          <td>{prec:.4f}</td>
          <td>{rec:.4f}</td>
          <td>{tpr1:.4f}</td>
        </tr>"""

    # ── Model accuracy cards ────────────────────────────────────────────
    accuracy_cards = ""
    if model_accuracy:
        for k, v in model_accuracy.items():
            accuracy_cards += f"""
            <div class="stat-card">
              <div class="stat-label">{k.title()} Model Accuracy</div>
              <div class="stat-value">{v:.4f}</div>
            </div>"""

    # ── DP section ──────────────────────────────────────────────────────
    dp_section = ""
    if dp_attack_results and dp_attack_metrics:
        eps_str = f"ε = {epsilon:.2f}" if epsilon is not None else "DP"
        dp_rows = ""
        for name in attack_metrics:
            if name not in dp_attack_metrics:
                continue
            label = _ATTACK_LABELS.get(name, name)
            base_auc = attack_metrics[name].get("auc_roc", 0.0)
            dp_auc = dp_attack_metrics[name].get("auc_roc", 0.0)
            reduction = base_auc - dp_auc
            sign = "+" if reduction > 0 else ""
            cls = "good" if reduction > 0.02 else "neutral"
            dp_rows += f"""
            <tr>
              <td class="name-cell">{label}</td>
              <td>{base_auc:.4f}</td>
              <td>{dp_auc:.4f}</td>
              <td class="{cls}">{sign}{reduction:.4f}</td>
            </tr>"""

        dp_section = f"""
        <section>
          <h2>🛡️ Differential Privacy Comparison ({eps_str})</h2>
          <p class="section-sub">
            AUC-ROC before and after DP training. Positive reduction = DP helped.
          </p>
          {f'<div class="chart-row"><div class="chart-wrap">{dp_comp_svg}</div></div>' if dp_comp_svg else ""}
          <table>
            <thead>
              <tr>
                <th>Attack</th>
                <th>Baseline AUC</th>
                <th>DP AUC ({eps_str})</th>
                <th>Reduction</th>
              </tr>
            </thead>
            <tbody>{dp_rows}</tbody>
          </table>
        </section>"""

    # ── Recommendations ─────────────────────────────────────────────────
    max_auc = max((m.get("auc_roc", 0.0) for m in attack_metrics.values()), default=0.0)
    if max_auc >= 0.75:
        recs = [
            "Train with Differential Privacy (target ε = 1–3 for strong protection).",
            "Reduce the number of training epochs — overfitting amplifies leakage.",
            "Add dropout and L2 regularisation to reduce memorisation.",
        ]
    elif max_auc >= 0.55:
        recs = [
            "Consider DP training with a moderate budget (ε = 5–10).",
            "Early stopping can reduce overfitting and leakage.",
            "Evaluate whether the model needs retraining with less sensitive data.",
        ]
    else:
        recs = [
            "No action required — leakage is within acceptable bounds.",
            "Continue monitoring with each new model version.",
        ]
    rec_items = "".join(f"<li>{r}</li>" for r in recs)

    # ── Distribution charts HTML ─────────────────────────────────────────
    dist_html = ""
    if dist_svgs:
        dist_html = '<div class="chart-row">'
        for label, svg in dist_svgs:
            dist_html += f'<div class="chart-wrap">{svg}</div>'
        dist_html += "</div>"

    # ══════════════════════════════════════════════════════════════════════
    # Full HTML
    # ══════════════════════════════════════════════════════════════════════
    html = textwrap.dedent(f"""\
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>AuditML Report — {experiment_name}</title>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />
      <style>
        *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
        :root {{
          --bg: #ffffff; --bg-subtle: #f8fafc; --bg-muted: #f1f5f9;
          --border: #e2e8f0; --text: #0f172a; --text-2: #475569;
          --text-3: #94a3b8; --accent: #6366f1;
        }}
        body {{ font-family: 'Inter', sans-serif; background: var(--bg); color: var(--text);
                line-height: 1.6; -webkit-font-smoothing: antialiased; max-width: 1100px;
                margin: 0 auto; padding: 2rem 1.5rem 4rem; }}

        /* header */
        .report-header {{ border-bottom: 2px solid var(--border); padding-bottom: 1.5rem; margin-bottom: 2rem; }}
        .report-header h1 {{ font-size: 1.75rem; font-weight: 800; letter-spacing: -0.02em; }}
        .report-meta {{ font-size: 0.88rem; color: var(--text-2); margin-top: 0.35rem; }}
        .report-meta span {{ margin-right: 1.25rem; }}

        /* top cards */
        .cards-row {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
                      gap: 1rem; margin-bottom: 2.5rem; }}
        .stat-card {{ background: var(--bg-subtle); border: 1px solid var(--border);
                      border-radius: 12px; padding: 1.25rem 1.5rem; }}
        .stat-label {{ font-size: 0.78rem; font-weight: 600; color: var(--text-2);
                       text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.4rem; }}
        .stat-value {{ font-size: 1.6rem; font-weight: 800; letter-spacing: -0.02em; }}

        /* risk card */
        .risk-card {{ border-radius: 12px; padding: 1.25rem 1.5rem; }}
        .risk-safe     {{ background: #dcfce7; border: 1px solid #bbf7d0; color: #166534; }}
        .risk-low      {{ background: #fef9c3; border: 1px solid #fde047; color: #854d0e; }}
        .risk-moderate {{ background: #fef3c7; border: 1px solid #fcd34d; color: #92400e; }}
        .risk-high     {{ background: #fee2e2; border: 1px solid #fca5a5; color: #991b1b; }}
        .risk-unknown  {{ background: var(--bg-muted); border: 1px solid var(--border); color: var(--text-2); }}
        .risk-label {{ font-size: 1rem; font-weight: 800; margin-bottom: 0.2rem; }}
        .risk-desc  {{ font-size: 0.85rem; font-weight: 500; }}

        /* sections */
        section {{ margin-bottom: 3rem; }}
        section h2 {{ font-size: 1.2rem; font-weight: 700; margin-bottom: 0.5rem;
                      letter-spacing: -0.01em; }}
        .section-sub {{ font-size: 0.9rem; color: var(--text-2); margin-bottom: 1.25rem; }}

        /* table */
        table {{ width: 100%; border-collapse: collapse; font-size: 0.9rem; }}
        thead th {{ background: var(--bg-subtle); padding: 0.6rem 0.9rem; text-align: left;
                    font-size: 0.78rem; font-weight: 700; color: var(--text-2);
                    text-transform: uppercase; letter-spacing: 0.05em;
                    border-bottom: 1px solid var(--border); }}
        tbody tr {{ border-bottom: 1px solid var(--border); transition: background 0.1s; }}
        tbody tr:hover {{ background: var(--bg-subtle); }}
        tbody td {{ padding: 0.65rem 0.9rem; }}
        .name-cell {{ font-weight: 600; color: var(--text); }}

        /* badges */
        .badge {{ display: inline-block; padding: 0.15rem 0.55rem; border-radius: 999px;
                  font-size: 0.82rem; font-weight: 700; }}
        .badge-green  {{ background: #dcfce7; color: #166534; }}
        .badge-yellow {{ background: #fef9c3; color: #854d0e; }}
        .badge-orange {{ background: #ffedd5; color: #9a3412; }}
        .badge-red    {{ background: #fee2e2; color: #991b1b; }}

        /* dp table */
        td.good    {{ color: #166534; font-weight: 700; }}
        td.neutral {{ color: var(--text-2); }}

        /* charts */
        .chart-row {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
                      gap: 1.5rem; margin-bottom: 1.5rem; }}
        .chart-wrap {{ background: var(--bg-subtle); border: 1px solid var(--border);
                       border-radius: 12px; padding: 1rem; overflow: hidden; }}
        .chart-wrap svg {{ width: 100%; height: auto; display: block; }}

        /* model inversion */
        .recon-grid {{ display: flex; flex-wrap: wrap; gap: 1rem; }}
        .recon-card {{ background: #0f172a; border-radius: 10px; padding: 0.75rem;
                       text-align: center; min-width: 100px; }}
        .recon-card img {{ width: 80px; height: 80px; display: block; margin: 0 auto 0.5rem; border-radius: 6px; }}
        .recon-label {{ font-size: 0.78rem; color: #94a3b8; font-weight: 600; }}
        .recon-conf  {{ font-size: 0.82rem; color: #34d399; font-weight: 700; font-family: 'JetBrains Mono', monospace; }}

        /* recommendations */
        .rec-list {{ list-style: none; display: flex; flex-direction: column; gap: 0.6rem; }}
        .rec-list li {{ padding: 0.65rem 1rem; background: var(--bg-subtle);
                        border-left: 3px solid var(--accent); border-radius: 0 8px 8px 0;
                        font-size: 0.9rem; color: var(--text-2); }}

        /* save button */
        .toolbar {{ display: flex; justify-content: flex-end; margin-bottom: 1.5rem; }}
        .save-btn {{ background: var(--accent); color: white; border: none; border-radius: 8px;
                     padding: 0.55rem 1.25rem; font-size: 0.9rem; font-weight: 600;
                     cursor: pointer; font-family: 'Inter', sans-serif;
                     transition: opacity 0.15s; }}
        .save-btn:hover {{ opacity: 0.85; }}

        /* footer */
        .report-footer {{ border-top: 1px solid var(--border); padding-top: 1.25rem;
                          font-size: 0.82rem; color: var(--text-3); text-align: center; }}

        @media (max-width: 640px) {{
          .cards-row {{ grid-template-columns: 1fr 1fr; }}
          .chart-row {{ grid-template-columns: 1fr; }}
        }}
      </style>
    </head>
    <body>

    <!-- TOOLBAR -->
    <div class="toolbar">
      <button class="save-btn" onclick="
        const a = document.createElement('a');
        a.href = URL.createObjectURL(new Blob([document.documentElement.outerHTML], {{type:'text/html'}}));
        a.download = '{experiment_name}_report.html';
        a.click();
      ">⬇ Save Report</button>
    </div>

    <!-- HEADER -->
    <div class="report-header">
      <h1>🔒 AuditML Privacy Report</h1>
      <div class="report-meta">
        <span><strong>Experiment:</strong> {experiment_name}</span>
        <span><strong>Generated:</strong> {timestamp}</span>
        <span><strong>Attacks run:</strong> {len(attack_metrics)}</span>
      </div>
    </div>

    <!-- SUMMARY CARDS -->
    <div class="cards-row">
      <div class="stat-card risk-card {risk_cls}">
        <div class="risk-label">{risk_label}</div>
        <div class="risk-desc">{risk_desc}</div>
      </div>
      {accuracy_cards}
      <div class="stat-card">
        <div class="stat-label">Attacks Run</div>
        <div class="stat-value">{len(attack_metrics)}</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">DP Comparison</div>
        <div class="stat-value">{'✓' if dp_attack_results else '—'}</div>
      </div>
    </div>

    <!-- ATTACK METRICS TABLE -->
    <section>
      <h2>⚔️ Attack Results</h2>
      <p class="section-sub">AUC-ROC above 0.55 indicates detectable privacy leakage. Above 0.75 is high risk.</p>
      <table>
        <thead>
          <tr>
            <th>Attack</th><th>Accuracy</th><th>AUC-ROC</th>
            <th>F1</th><th>Precision</th><th>Recall</th><th>TPR@1%FPR</th>
          </tr>
        </thead>
        <tbody>{table_rows}</tbody>
      </table>
    </section>

    <!-- ROC CURVES + SCORE DISTRIBUTIONS -->
    {f'''<section>
      <h2>📈 ROC Curves &amp; Score Distributions</h2>
      <p class="section-sub">Left: ROC curves for all attacks. Right: member vs non-member confidence score overlap per attack — more overlap = lower leakage.</p>
      <div class="chart-row">
        <div class="chart-wrap">{roc_svg}</div>
        {"".join(f'<div class="chart-wrap">{s}</div>' for _, s in dist_svgs[:1])}
      </div>
      {"".join(f'<div class="chart-row"><div class="chart-wrap">{s}</div></div>' for _, s in dist_svgs[1:])}
    </section>''' if roc_svg else ""}

    <!-- COMPARISON BAR -->
    {f'''<section>
      <h2>📊 Attack Comparison</h2>
      <p class="section-sub">AUC-ROC by attack type. Green (&lt;0.55) = safe, yellow = low, orange = moderate, red = high.</p>
      <div class="chart-row"><div class="chart-wrap">{comp_svg}</div></div>
    </section>''' if comp_svg else ""}

    <!-- MODEL INVERSION RECONSTRUCTIONS -->
    {recon_html}

    <!-- DP COMPARISON -->
    {dp_section}

    <!-- RECOMMENDATIONS -->
    <section>
      <h2>💡 Recommendations</h2>
      <ul class="rec-list">{rec_items}</ul>
    </section>

    <div class="report-footer">
      Generated by <strong>AuditML</strong> · MIT License ·
      <a href="https://github.com/EemanAsghar/AuditML" style="color:var(--accent)">GitHub</a>
    </div>

    </body>
    </html>
    """)

    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / "report.html"
    out_path.write_text(html, encoding="utf-8")
    return out_path
